workspace:
  base: /test
  path: oe-poetry-behat

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    environment:
      - DOCUMENT_ROOT=/test/oe-poetry-behat

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    volumes:
      - /cache:/cache
    commands:
      - composer update ${COMPOSER_BOUNDARY}

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./vendor/bin/behat

matrix:
  IMAGE_PHP:
    - fpfis/httpd-php-dev:5.6
    - fpfis/httpd-php-dev:7.1
  COMPOSER_BOUNDARY:
    - '--prefer-lowest'
    - ''
