workspace:
  base: /test
  path: oe-poetry-behat

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php:5.6}
    environment:
      - DOCUMENT_ROOT=/test/oe-poetry-behat

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php:5.6}
    volumes:
      - /cache:/cache
    commands:
      - composer self-update
      - composer install

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php:5.6}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php:5.6}
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php:5.6}
    commands:
      - ./vendor/bin/behat

matrix:
  IMAGE_PHP:
    - fpfis/httpd-php:5.6
    - fpfis/httpd-php:7.1
