language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/grumphp run
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat

notifications:
  email: false
